Numpy is the fundamental package for numeric compting with Python. It provides powerful ways to create, store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety of databases and data formats. This is also the foundation that Pandas is built on which is a high performance data-centric package.

In [72]:
import numpy as np
import math 

# Array Creation 

In [73]:
a = np.array([1, 2, 3])
print(a)
#no. of dimensions of a list using ndim
print(a.ndim) 

[1 2 3]
1


In [74]:
# multi-dimensional array
b= np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
#length of each dimension by calling the shape attribute, which returns a tuple
b.shape

(2, 3)

In [76]:
#type of items in the array
a.dtype

dtype('int32')

In [77]:
#float is acceptect
c= np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [78]:
c

#automatically converts 5 to floats since there is no loss of precision
#numpy gives the best data type format possible to keep your data types homogeneous

array([2.2, 5. , 1.1])

In [79]:
#creating two arrays, both the same shape but with diff filler values

d= np.zeros ((2,3))
print(d) 

e= np.ones ((2,3)) 
print(e) 

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [80]:
#randomize 

np.random.rand(2,3) 

array([[0.48439803, 0.89263508, 0.13998362],
       [0.14795639, 0.86252539, 0.38608218]])

In [81]:
#sequence of nunmbers in an array with the arrange() function. 

#array of every even number from ten (inclusive) to fifty (exclusive) 
f= np.arange(10, 50, 2) 
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [82]:
#generate a sequence of floats with a linspace() function. 

np.linspace(0, 2, 15) # 15 no. from 0 (inclusive) to 2 (inclusive) 

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array Operations

In [83]:
#arithmetric operators on array apply elementwise. 

a = np.array([10,20,30,40]) 
b = np.array([4,3,2,1])

c = a-b 
d = a*b 

print(c)
print(d)

[ 6 17 28 39]
[40 60 60 40]


In [84]:
#array of typical winter farenheit values

farenheit = np.array([0,-10, -5, -15, 0])

celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [85]:
celcius > -20 


array([ True, False, False, False,  True])

In [86]:
celcius %2==0

array([False, False,  True, False, False])

In [87]:
#matrix manipulation 
g = np.array([[1,1], [0,1]])
h = np.array([[2,3], [9,5]])

print(g*h) 

# the '@' sign or dot function is utilized when we want to do matrix product
print(g@h) 

[[2 3]
 [0 5]]
[[11  8]
 [ 9  5]]


In [88]:
#shape of the matrix
g.shape

(2, 2)

In [89]:
# Upcasting. When manipulating arrays of different types, the type of the resulting array 
# will correspond to the more general of the two types.
array1= np.array([[1,2,3], [4,5,6]])
print(array1.dtype) 

array2 = np.array([[2.2, 5, 1.1], [2.2, 5, 1.1]])
print(array2.dtype)



int32
float64


In [90]:
array3 = array1 + array2
print(array3) 
print(array3.dtype) 


[[ 3.2  7.   4.1]
 [ 6.2 10.   7.1]]
float64


In [91]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

37.6
10.0
3.2
6.266666666666667


In [92]:
b= np.arange(1,16,1). reshape(3,5) 
print(b) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [1]:
!pip install pillow

In [2]:
from PIL import Image
from IPython.display import display

im = Image.open('files.png') 
display(im) 

ModuleNotFoundError: No module named 'PIL'

In [ ]:
array = np.array(im) 
print(array.shape) 
array

In [ ]:
# for black and white images is stored as 0 and white is stored as 255. So if we just wanted 
# to invert the image we use the numpy array to do so

#sample
mask= np.full(array.shape,255) 
mask 

In [ ]:
modified_array = array- mask
modified_array = modified_array*-1 
modified_array = modified_array.astype(np.uint8) 

modified_array

In [ ]:
display(Image.fromarray(modified_array))

In [ ]:
reshaped= np.rreshape(modified_array, (100, 400))
print(reshaped.shape) 
display(Image.fromarray(reshaped))


# Indexing, Slicing and Iterating 

In [1]:
# Indexing, slicing and iterating are extremely important for data mannipulation and analysis 
# because these techniques allow us select data based on conditions, and copy or update data.

## Indexing

In [3]:
# On-demensional array, works in similar ways as a list- to get an element in a one-dimensional
# array, we simply use the offset index. 
import numpy as np
a = np.array([1,3,5,7]) 
a[2]

5

In [6]:
# Multidimensional array, we need to use integer array indexing
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# if we want to select one certain element, we can do so by entering the index, which is comprised
# of two integers the first being the being the row, and the second the column

a[1,1]

4

In [8]:
print(a[[0, 1, 2], [0, 1, 1]])

[1 4 6]


## Boolean Indexing 

In [9]:
# Boolean indexing allows us to select arbitrary elements based on conditions.
print (a >5)

[[False False]
 [False False]
 [False  True]]


In [10]:
# mask over the original array to return a one-dimensional array relation to the true values. 

print (a[a>5])

[6]


In [11]:
# This functionality is essential in the pandas toolkit which is the bulk of this course

## Slicing

In [13]:
# Slicing is a way to create a sub-array based on the original array.
# For one-dimensional arrays, slicing works in similar ways to a list.
# To slice, we use the : sign. For instance, if we put : 3 in the indexing brackets, 
# we get elements from index 0 to index 3 (excluding index 3) 

a = np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [14]:
print(a[2:4]) 

[2 3]


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[:2] 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
a[:2, 1:3] 

array([[2, 3],
       [6, 7]])

In [21]:
sub_array = a[:2, 1:3] 
print("Sub array index [0,0] value before change: ", sub_array[0,0]) 
sub_array[0,0] = 50 
print ("sub array index [0,0] value after change: ", sub_array[0,0]) 
print("Original array index [0,1] value after change: ", a[0,1]) 


Sub array index [0,0] value before change:  50
sub array index [0,0] value after change:  50
Original array index [0,1] value after change:  50


# Trying Numpy with Datasets

In [ ]:
# to load a dataset in Numpy, we can use the genfromtxt() function. 